"""Lisätty team_association

Revision ID: 06b87e89b060
Revises: 1aff7606fcc1
Create Date: 2024-11-10 23:15:25.503143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06b87e89b060'
down_revision = '1aff7606fcc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.add_column(sa.Column('team_association', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.drop_column('team_association')

    # ### end Alembic commands ###
