"""Initial migration

Revision ID: 06e70ad72171
Revises: 
Create Date: 2025-01-08 22:06:32.021516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06e70ad72171'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.drop_constraint('uq_team_id_stat_group', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_team_id_stat_group', ['team_id', 'stat_group'])

    # ### end Alembic commands ###
