"""tilapäistiedoston poistaminen

Revision ID: 15a75bdd3d3d
Revises: ea48ed0c9776
Create Date: 2025-01-16 21:00:25.017621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15a75bdd3d3d'
down_revision = 'ea48ed0c9776'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('temporary_field')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('temporary_field', sa.VARCHAR(length=100), nullable=True))

    # ### end Alembic commands ###
