"""Lisätty joukkueiden taulukkoon season ja level_id

Revision ID: 1aff7606fcc1
Revises: e2cacdd0a047
Create Date: 2024-11-10 22:30:59.096948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1aff7606fcc1'
down_revision = 'e2cacdd0a047'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.add_column(sa.Column('season', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('level_id', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.drop_column('level_id')
        batch_op.drop_column('season')

    # ### end Alembic commands ###
