"""Reinitialized migrations 2

Revision ID: 21657af53c7f
Revises: d7fab61b5ec6
Create Date: 2025-02-19 09:32:39.863014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21657af53c7f'
down_revision = 'd7fab61b5ec6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tgames', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sortable_date2', sa.String(length=150), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tgames', schema=None) as batch_op:
        batch_op.drop_column('sortable_date2')

    # ### end Alembic commands ###
