"""Lisätty Jopox team name

Revision ID: 23eea08a5e6c
Revises: 5dcaf4e2c641
Create Date: 2024-12-28 20:19:45.402511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23eea08a5e6c'
down_revision = '5dcaf4e2c641'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jopox_team_name', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('jopox_team_name')

    # ### end Alembic commands ###
