"""Initial migration with updated user model

Revision ID: 382fe878585d
Revises: 
Create Date: 2024-11-03 22:15:57.518014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '382fe878585d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('managed_teams', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('followed_teams', sa.String(length=512), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('followed_teams')
        batch_op.drop_column('managed_teams')

    # ### end Alembic commands ###
