"""poistetaan tilapäinen rivi

Revision ID: 3873a6c777d9
Revises: 21657af53c7f
Create Date: 2025-02-19 09:34:04.529531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3873a6c777d9'
down_revision = '21657af53c7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
