"""Lisätty team_association ja statgroup

Revision ID: 41cdc6d440b6
Revises: 06b87e89b060
Create Date: 2024-11-11 18:18:53.424703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41cdc6d440b6'
down_revision = '06b87e89b060'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.add_column(sa.Column('statgroup', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.drop_column('statgroup')

    # ### end Alembic commands ###
