"""Lisätty Jopox team id

Revision ID: 5dcaf4e2c641
Revises: 41cdc6d440b6
Create Date: 2024-12-28 19:00:14.487527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5dcaf4e2c641'
down_revision = '41cdc6d440b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jopox_team_id', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('jopox_team_id')

    # ### end Alembic commands ###
