"""Initial migration after reset

Revision ID: 97328fd3d072
Revises: 
Create Date: 2025-03-26 19:04:31.076778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97328fd3d072'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.create_unique_constraint("uq_team_team_id", ['team_id'])

    with op.batch_alter_table('tgames', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stat_group_name', sa.String(length=50), nullable=False, server_default='unknown'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tgames', schema=None) as batch_op:
        batch_op.drop_column('stat_group_name')

    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
