"""added jopox calendar url to user

Revision ID: 9766bf2f613c
Revises: ad5d2df2aef4
Create Date: 2025-02-21 23:37:31.882017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9766bf2f613c'
down_revision = 'ad5d2df2aef4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jopox_calendar_url', sa.String(length=150), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('jopox_calendar_url')

    # ### end Alembic commands ###
