"""user jopox_login_url added

Revision ID: ad5d2df2aef4
Revises: 73dff2f13c8b
Create Date: 2025-02-20 10:36:50.028250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad5d2df2aef4'
down_revision = '73dff2f13c8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
   
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jopox_login_url', sa.String(length=150), nullable=True))
        batch_op.alter_column('jopox_team_name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('jopox_username',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('jopox_username',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=150),
               existing_nullable=True)
        batch_op.alter_column('jopox_team_name',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.drop_column('jopox_login_url')

    # ### end Alembic commands ###
