"""Reinitialized migrations

Revision ID: d7fab61b5ec6
Revises: 
Create Date: 2025-02-18 13:33:39.448653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7fab61b5ec6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tgames', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sortable_date2', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tgames', schema=None) as batch_op:
        batch_op.drop_column('sortable_date2')

    # ### end Alembic commands ###
