# Tämä kommentti pakottaa Gitin näkemään tiedoston muuttuneena


"""Allow same team_id with different stat_groups

Revision ID: e1db518314db
Revises: 97328fd3d072
Create Date: 2025-03-26 22:29:45.719710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1db518314db'
down_revision = '97328fd3d072'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.drop_constraint('uq_team_team_id', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_team_team_id', ['team_id'])

    # ### end Alembic commands ###
