"""tietokannan luominen uudestaan

Revision ID: ea48ed0c9776
Revises: 
Create Date: 2025-01-16 20:59:32.970486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea48ed0c9776'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jopox_username', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('jopox_password', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('temporary_field', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('temporary_field')
        batch_op.drop_column('jopox_password')
        batch_op.drop_column('jopox_username')

    # ### end Alembic commands ###
