"""jopoxlaskurin lisäys

Revision ID: f34ebefe52f7
Revises: 6a369bb41b92
Create Date: 2025-09-12 09:11:25.646292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f34ebefe52f7'
down_revision = '6a369bb41b92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_jopox_entries', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('edited_jopox_entries', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('edited_jopox_entries')
        batch_op.drop_column('created_jopox_entries')

    # ### end Alembic commands ###
