"""lisää jopox_uid tgames-tauluun

Revision ID: fdb3e9ebf2df
Revises: f34ebefe52f7
Create Date: 2026-07-02 18:41:35.943409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdb3e9ebf2df'
down_revision = 'f34ebefe52f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tgames', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jopox_uid', sa.String(length=50), nullable=True))
        batch_op.create_index(batch_op.f('ix_tgames_jopox_uid'), ['jopox_uid'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tgames', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tgames_jopox_uid'))
        batch_op.drop_column('jopox_uid')

    # ### end Alembic commands ###
